### ISSUE TITLE
[BUG] `GLIBC_2.29` not found in Ubuntu 18.04

### ISSUE THREAD

**Issue by secsilm** [mosecorg/mosec#107]
**Describe the bug**
mosec will raise the following error in Ubuntu 18.04:

```
/data/anaconda3/envs/mosec-p38/lib/python3.8/site-packages/mosec/bin/mosec: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /data/anaconda3/envs/mosec-p38/lib/python3.8/site-packages/mosec/bin/mosec)
```

**To Reproduce**
Just run the [Sentiment Analysis](https://mosecorg.github.io/mosec/example/pytorch/#sentiment-analysis) example.

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Library Version: 0.2.1
 - Rust Version: unknown
 - Python Version: 3.8.12

**Additional context**
I tried to use mosec in Ubuntu 20.04 and it worked. So if Ubuntu 20.04 or above is required, I think it's better to put it on the document.

**Comment by lkevinzc** [comment]
Hi @secsilm , thanks for the feedback!

Bug reproduced on the given setting. The cause should be that our build was based on ubuntu20, will try to fix it soon :)

**Comment by lkevinzc** [comment]
Hi @secsilm , please have a check with `pip install mosec==0.3.1a1`, and from this version on we should be able to support ubuntu18.04 onwards.

PS: 
1. 0.2.x -> 0.3.x: we add `pyarrow.plasma` as shared memory for IPC;
2. 0.3.1a1 (pre-release): we haven't fully resolved the troublesome CI test for MacOC on github action...

**Comment by secsilm** [comment]
The version 0.3.1 is not available on PyPi for now. I'll try it when it's released.

**Comment by kemingy** [comment]
> The version 0.3.1 is not available on PyPi for now. I'll try it when it's released.

It should be available now: https://pypi.org/project/mosec/0.3.1/#files

**Comment by secsilm** [comment]
> > The version 0.3.1 is not available on PyPi for now. I'll try it when it's released.
> 
> It should be available now: https://pypi.org/project/mosec/0.3.1/#files

Thanks for your quick response. I tried it again and it worked in Ubuntu 18.04. Thank you!
