### ISSUE TITLE
[FEATURE]Benchmark for AI system

### ISSUE THREAD

**Issue by ShiyangZhang** [mosecorg/mosec#123]
Our community lacks some benchmark for server-side end to end AI system. For examples, the [face recognition system](https://github.com/deepinsight/insightface), smart tracfic system with tens of models, and [ocr-system](https://github.com/PaddlePaddle/PaddleOCR). A complete comparison  for the throughout and Latency across different  hardware platforms and  also libraries is necessary. Usability might also be  considered.  This is both beneficial to hardware manufactures, and also Democratisation of AI.

**Comment by kemingy** [comment]
I also hope there is a benchmark like [TechEmpower](https://www.techempower.com/benchmarks/) but for ML services. But I don't have the machine resource to do so.

**Comment by ShiyangZhang** [comment]
> TechEmpower

Do you have any plan to benchmark mosec for rps, TP50, TP90, and so on?

**Comment by kemingy** [comment]
I have done some benchmarks for Mosec during development. Including the RPS, P99 P50 latency, CPU usage, memory consumption, etc.

I'm not sure if you have a general scenario to compare these frameworks.

**Comment by ShiyangZhang** [comment]
> 

Hi, 
Are these benchmarks publicly available?

> I'm not sure if you have a general scenario to compare these frameworks.
One may compare end to end [face recognition system](https://github.com/deepinsight/insightface) between triton server and [mosec](https://github.com/mosecorg/mosec).

Best,

**Comment by lkevinzc** [comment]
Hi @ShiyangZhang , thank you for your suggestions.

Personally I think it's pretty hard to well benchmark different serving frameworks for different applications.

Different applications (with different scales, say, serving 100 QPS or 5k QPS) may have quite different requirements for the underlying serving framework. Some are cpu-bound, some are gpu-bound, and others may be network-bound. Besides, some applications may even need a more complicated system to e.g., 1) support a cache layer, 2) load-balancing different workloads, etc.

I believe different serving frameworks will suit different needs. 

In our case, we design mosec as a lightweight and user-friendly serving framework, which requires very minimal modification to easily serve your model in pure python with rust as network backend. We think our design is achieving a good balance between complexity and performance, and it is particularly suitable for serving a model as a micro-service. As you may notice, it is not as easy to use the triton inference server you mentioned as using ours one.

I think you may base on your scenario and choose the one that is suitable to you. And you could host your own application using mosec and measure the performance. We will be very glad to improve our framework if the performance is not as good as expected. Thanks! :)

**Comment by ShiyangZhang** [comment]
> 
Hi, 
Thanks for your reply and clear explanation for the purpose of mosec. I do agree that for some complex scenario and for whom care much about the performance and expecially,  flexibility, mosec would be quite helpful.  And we would see more and more exploration into this direction, for example, [Paddle Serving](https://github.com/PaddlePaddle/Serving),  openvinoserver,   TORCHSERVE, 
 AI-Express, [videoflow](https://openreview.net/pdf?id=Rq31tXaqXq) , CNStream, nnstreamer, mediapipe, TengineInferPipe. I think it would be a long story.
