### ISSUE TITLE
[FEATURE] add more useful worker classes

### ISSUE THREAD

**Issue by kemingy** [mosecorg/mosec#138]
So far, there is only one `Worker` base type with JSON serialization and Pickle IPC serialization.

- [x] #139
- [x] #140

**Comment by gaocegege** [comment]
I think we can add some docs for the worker types. I did not get the differences between JSON and Pickle before we discussed them offline.

**Comment by kemingy** [comment]
> I think we can add some docs for the worker types. I did not get the differences between JSON and Pickle before we discussed them offline.

Yeah. Although we have the doc, but it's not straightforward. I'm planning to draw a flowchart to demonstrate the main features.

**Comment by kemingy** [comment]
BTW, it should be a mixin. Check https://stackoverflow.com/a/547714

**Comment by lkevinzc** [comment]
> BTW, it should be a mixin. Check https://stackoverflow.com/a/547714

Yea agree, this looks better.
