### ISSUE TITLE
[typo] Wrong key word `path` in workflows

### ISSUE THREAD

**Issue by gaocegege** [mosecorg/mosec#144]
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-including-paths

https://github.com/mosecorg/mosec/blob/main/.github/workflows/check.yml#L6

path is not supported by GitHub actions, we should use `paths`

**Comment by kemingy** [comment]
No wonder it doesn't work.

Thanks for pointing it out.
