### ISSUE TITLE
[FIX] python package: including rust source files

### ISSUE THREAD

**Issue by kemingy** [mosecorg/mosec#146]
I just found that this doesn't really fix this issue.

Python package is unpredictable. :(

_Originally posted by @kemingy in https://github.com/mosecorg/mosec/issues/127#issuecomment-1151181557_

**Comment by kemingy** [comment]
Ref:

* https://github.com/abravalheri/experiment-setuptools-package-data
* https://github.com/pypa/setuptools/issues/2710

**Comment by lkevinzc** [comment]
> 

Learned this. BTW it looks good currently on PyPI:
![image](https://user-images.githubusercontent.com/38581401/172984759-bea7a761-aea1-402b-922a-7ef25d86955e.png)
