### ISSUE TITLE
adopt the official Rust Prometheus client

### ISSUE THREAD

**Issue by kemingy** [mosecorg/mosec#186]
* refer to https://github.com/tikv/rust-prometheus/issues/392
* https://github.com/prometheus/client_rust

**Comment by AlexXi19** [comment]
Is this issue to switch from https://github.com/tikv/rust-prometheus to https://github.com/prometheus/client_rust?

**Comment by kemingy** [comment]
> Is this issue to switch from https://github.com/tikv/rust-prometheus to https://github.com/prometheus/client_rust?

Yes
