### ISSUE TITLE
security: RUSTSEC-2021-0139

### ISSUE THREAD

**Issue by kemingy** [mosecorg/mosec#218]
This has been fixed in https://github.com/tokio-rs/tracing/pull/2287, but I don't know when will they create a new tracing-subscriber release. Since this one may need some backports.

Tracked in https://github.com/tokio-rs/tracing/issues/2282.

BTW, we haven't used any of the trace features of tracing. We only use it for logging. We can explore more about the trace features.

**Comment by lkevinzc** [comment]
> BTW, we haven't used any of the trace features of tracing. We only use it for logging. We can explore more about the trace features.

Sounds good, as long as enabling it won't affect latency.
