### ISSUE TITLE
[FEATURE] Ability to add additional arguments

### ISSUE THREAD

**Issue by aditya140** [mosecorg/mosec#267]
## Description

The way arguments are parsed by mosec library, does not support arguments apart from the ones mentioned at https://mosecorg.github.io/mosec/argument/ .

I was trying to use mosec as an inference server for a larger project. I already have multiple arguments that I pass to the python file to start the server.  Can't figure out how to pass the additional arguments.

## Possible Solutions

I try to get around this by modifying the https://github.com/mosecorg/mosec/blob/main/mosec/args.py file.
Changing    
```args = parser.parse_args()``` to ```args, unk_args = parser.parse_known_args()``` lets me add my own arguments in my project.

Haven't explored any other alternatives, but suggestions are welcome

**Comment by aditya140** [comment]
Huge thanks to the people developing this project. Have started using mosec recently for a project and am loving the flexibility provided by mosec, while abstracting the dynamic batching part.

**Comment by kemingy** [comment]
Thanks for your feedback. I'd like to know more information about the existing arguments.

- Is it also using Python's built-in argparse library?
- Is it called before mosec `server.run()`?

**Comment by aditya140** [comment]
Thanks for your reply.

- Yes, i am also using the built-in argparse library.
- Yes, the arguments I am trying to parse are before I call ```server.run()```

**Comment by kemingy** [comment]
> Thanks for your reply.
> 
>     * Yes, i am also using the built-in argparse library.
> 
>     * Yes, the arguments I am trying to parse are before I call `server.run()`

In this case, I think both your own arg parser and mosec should use `args, unk_args = parser.parse_known_args()` to make it work.

Let me create a PR to fix this.
