### ISSUE TITLE
[FEATURE] Streaming output

### ISSUE THREAD

**Issue by VoVAllen** [mosecorg/mosec#273]
Triton supports returning the response in stream by `triton_client.async_stream_infer`. Hope mosec can have a similar function, which is useful for language models

**Comment by txsun1997** [comment]
@VoVAllen  this would be necessary to support streaming response for large language models as they usually require a longer response time, which wears down users' patience. In this case, generating the response in the stream (e.g., word by word) would significantly improve users' experience. Btw, ChatGPT is exactly acting like this.

**Comment by gaocegege** [comment]
```
curl 'https://chat.openai.com/backend-api/conversation' \
  -H 'authority: chat.openai.com' \
  -H 'accept: text/event-stream' \
  -H 'accept-language: zh-CN,zh;q=0.9' \
  -H 'content-type: application/json' \
  -H 'origin: https://chat.openai.com' \
  -H 'referer: https://chat.openai.com/chat' \
  -H 'sec-ch-ua: "Google Chrome";v="105", "Not)A;Brand";v="8", "Chromium";v="105"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: "Linux"' \
  -H 'sec-fetch-dest: empty' \
  -H 'sec-fetch-mode: cors' \
  -H 'sec-fetch-site: same-origin' \
  -H 'user-agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36' \
  --data-raw '{"action":"next","messages":[{"id":"1a5f62f1-9c1a-4485-8f74-df2fd3723589","role":"user","content":{"content_type":"text","parts":["envd is here https://github.com/tensorchord/envd\n"]}}],"conversation_id":"409004f7-0e7e-4b66-a264-09bd909d12db","parent_message_id":"6db6f583-d9d0-430a-a929-d3a4be84e75a","model":"text-davinci-002-render-sha"}' \
  --compressed
```

This is the ChatGPT request

It is a `text/event-stream'` req

**Comment by kemingy** [comment]
I will work on this one.

So far, [SSE](https://en.wikipedia.org/wiki/Server-sent_events) should be enough for this feature.

/assign

**Comment by VoVAllen** [comment]
I think supporting websocket like MOSS did would be a more elegant solution than using SSE. Just let mosec spin up multiple ws is enough for streaming output.


Pros of ws:
- Disentangle with the inference endpoint. More flexibility, such as mixing streaming output with non-streaming output.
- More control of the inference process. For example, user can use custom protocol to interrupt the streaming inference process if needed. 
- `ws.write_msg` is more intuitive than writing generator with `yield xxx`, and much easier to understand

**Comment by kemingy** [comment]
> I think supporting websocket like MOSS did would be a more elegant solution than using SSE. Just let mosec spin up multiple ws is enough for streaming output.

Do you mean we don't need to add any features? Because WebSocket is more like user's choice. Nothing prevents users from adding another communication tunnel like WebSocket or gRPC or something else.

**Comment by VoVAllen** [comment]
Mosec can add ws ability so that ws can be on the same endpoint (or same port) instead of a new port. And mosec can provide wrapper in client SDK to enable user to use streaming without knowing websockets. Otherwise, I think it's hard to support both streaming and non-streaming scenario in the same function.
This is also "make the easy things easy, and the hard things possible".

**Comment by kemingy** [comment]
> Mosec can add ws ability so that ws can be on the same endpoint (or same port) instead of a new port. And mosec can provide wrapper in client SDK to enable user to use streaming without knowing websockets. Otherwise, I think it's hard to support both streaming and non-streaming scenario in the same function. This is also "make the easy things easy, and the hard things possible".

But how?

- Do you mean add WebSocket to the rust web layer?
- If we accept streaming input, how can we know which part should be dynamically batched? If we know, then it might be possible to support both streaming and non-streaming simultaneously (maybe in different functions).
- We don't provide SDK because we don't know which language to support, also HTTP is a general one so we don't need to write an HTTP client SDK.
