### ISSUE TITLE
feat: Keep the same prefix in python and rust log

### ISSUE THREAD

**Issue by gaocegege** [mosecorg/mosec#289]
### Describe the feature

Keep the same prefix in python and rust.

### Why do you need this feature?

I want to filter mosec log and user invoked log.

**Comment by kemingy** [comment]
It's harder than I expected. Python logging module doesn't provide a convenient function to handle it.

In short, I don't know how to get the library name from the `logging.LogRecord`. A dirty way is `'/mosec/' in record.pathname` which can be wrong if the code absolute path contains `/mosec/`.

Welcome suggestions.

**Comment by kemingy** [comment]
I guess we need to create another logger for internal usage that has a special `target` in the JSON output.
