### ISSUE TITLE
feat: support a dryrun test

### ISSUE THREAD

**Issue by lkevinzc** [mosecorg/mosec#296]
### Describe the feature

Use an argument flag to enable the dryrun test, which:
1. starts all stages with only 1 worker in it (force it to be 1, even users specify > 1, to prevent downloading lock mentioned in #286) **->** helping downloading files and so on
2. forwards the `example` (if any) in the ingress stage, and make it through all stages **->** helping debugging
3. report the results: a) errors if any; b) latency of each stage (after warmup)
4. finally exit the service

### Why do you need this feature?

* helping Mosec developers with their service debugging and quality assessment

**Comment by lkevinzc** [comment]
Some additional results can be gathered include:
- memory usage
- cpu usage
- GPU peak memory
- GPU utilization

**Comment by kemingy** [comment]
LGTM. 

BTW using only 1 worker for each stage won't prevent the issue mentioned in #286. Because the preprocessing and postprocessing workers can use the same tokenizer. But 1 worker should meet this debug purpose.

I guess we can add a `--dry-run` argument. WDYT.

**Comment by lkevinzc** [comment]
> Because the preprocessing and postprocessing workers can use the same tokenizer.
I think in this case uses should take care themselves. But at least from mosec side forcing single work is necessary.

> I guess we can add a `--dry-run` argument.
LGTM!

**Comment by kemingy** [comment]
I'll work on this. /assign
