### ISSUE TITLE
bug: <title> I want the program to do batching, why didn't my max_batch_size parameter work?

### ISSUE THREAD

**Issue by leap233** [mosecorg/mosec#338]
### Describe the bug

My example is referenced to the official website, I don't know why max_batch_size parameters don't work.

Here is an example of my code structure(server).
------------------------------------------------------------------
from io import BytesIO
from typing import List
from diffusers import StableDiffusionPipeline  # type: ignore
from mosec import Server, Worker, get_logger
from mosec.mixin import MsgpackMixin

class generate_test(MsgpackMixin, Worker):
  def __init__(self):
      pass
  
  def forward(self, data: List[str]) -> List[memoryview]:
      # resTextList = self.evaluate(data)
      resTextList = ["hello!!!!!!"]
      return resTextList
    
if __name__ == '__main__':
    server = Server()
    server.append_worker(generate_test, num=1, max_wait_time=10,max_batch_size=4)
    server.run()
--------------------------------------------------------
Here is an example of my code structure(client).
----------------------------------------------------------
resp = httpx.post(
    f"http://127.0.0.1:6000/inference",
    data=msgpack.packb('hello!'),
    timeout=httpx.Timeout(900.0),
)
if resp.status_code == 200:
    data = msgpack.unpackb(resp.content)
    print(data)
----------------------------------------------------
My expected goal is to batch 4 requests in 10 seconds and my model will process all four requests at the same time, but the current situation is that every time I request it, it processes it without waiting for other requests. That is to say, the data array always has only one string, why is that?

### To Reproduce

Call this server normally

### The mosec version

Name: mosec
Version: 0.6.5
Summary: Model Serving made Efficient in the Cloud
Home-page: https://github.com/mosecorg/mosec
Author: Keming Yang
Author-email: Keming <kemingy94@gmail.com>, Zichen <lkevinzc@gmail.com>
License: Apache-2.0
Location: /home/shun_wu/.local/lib/python3.8/site-packages
Requires: 
Required-by:

**Comment by kemingy** [comment]
The `max_wait_time` here is 10ms not 10s.

**Comment by leap233** [comment]
> 这里`max_wait_time`是 10ms 而不是 10s。

It worked, thanks!
