### ISSUE TITLE
feat: type check/validation for inference parameters

### ISSUE THREAD

**Issue by cutecutecat** [mosecorg/mosec#351]
### Describe the feature

Users will get confused with "500, 'inference internal error" when they send a wrong format parameters.
We could use some type hint check to announce users the right format.

## An idea from `pydantic`
```python
from functools import wraps
from mosec import ValidationError, Worker
from mosec.mixin import MsgpackMixin
from typing import Any, Dict, List, Literal, TypedDict
from pydantic import create_model_from_typeddict
import pydantic

# exported from mosec
class data_type_check(object):
    def __init__(self, data_type: type):
        self.data_type = data_type

    def __call__(self, func):
        @wraps(func)
        def wrapped_function(cls, data: Any):
            if not isinstance(data, self.data_type):
                # could extend ValidationError and display self.data_type
                raise ValidationError
            if isinstance(data, dict):
                self.validate_dict(data)
            # skip list validation for arbitrary length
            return func(cls, data)
        return wrapped_function

    def validate_dict(self, data: Dict):
        Model = create_model_from_typeddict(self.data_type)
        try:
            Model.parse_obj(data)
        except pydantic.error_wrappers.ValidationError:
            # could extend ValidationError and display Model.schema_json()
            raise ValidationError

# user code
class Input(TypedDict):
    task: Literal["image", "audio", "video", "text"]
    data: List[bytes | str]

class ImageBind(MsgpackMixin, Worker):
    def __init__(self):
        pass

    @data_type_check(data_type=Input)
    def forward(self, data: Input) -> List[List[float]]:
        pass
```

### Why do you need this feature?

Terminal user will get benefit from type validation, if model developer take a little time to define a schema.

**Comment by kemingy** [comment]
You don't need to write a decorator. Just use the mixin to override the `deserialize` method. It's more efficient to parse the raw bytes into the desired type than parsing an object after the deserialization.

BTW, in this case, [msgspec](https://jcristharif.com/msgspec/benchmarks.html) might be faster than pydantic v1.

**Comment by gaocegege** [comment]
I hope this feature is optional. We do not run type checks if the user does not add any type hint in the server code.

**Comment by kemingy** [comment]
Actually, typed input can also generate the OpenAPI doc. It's supported by pydantic/msgspec/etc.

**Comment by gaocegege** [comment]
> Actually, typed input can also generate the OpenAPI doc. It's supported by pydantic/msgspec/etc.

It's also useful to users. I think. We could generate the API doc from the server code.

**Comment by cutecutecat** [comment]
> You don't need to write a decorator. Just use the mixin to override the `deserialize` method. It's more efficient to parse the raw bytes into the desired type than parsing an object after the deserialization.
> 
> BTW, in this case, [msgspec](https://jcristharif.com/msgspec/benchmarks.html) might be faster than pydantic v1.

It's designed for endpoint users, when they write a request of the wrong format, they could receive some suggestion of the right `type schema` in response, instead of `inference internal error`.

`pydantic` could provide some schema json from its model, likes:
```json
{
	"title": "Input",
	"type": "object",
	"properties": {
		"task": {
			"title": "Task",
			"enum": ["image", "audio", "video", "text"],
			"type": "string"
		},
		"data": {
			"title": "Data",
			"type": "array",
			"items": {
				"anyOf": [{
					"type": "string",
					"format": "binary"
				}, {
					"type": "string"
				}]
			}
		}
	},
	"required": ["task", "data"]
}
```

This case usually happens when client and server are coded by different people.

**Comment by kemingy** [comment]
I don't see any conflicts between your comments and the quoted comments.

**Comment by cutecutecat** [comment]
> I don't see any conflicts between your comments and the quoted comments.

Sorry, I got it recently by read the doc. `msgspec` could do same thing and really faster.
Maybe we could insert an msgspec-based validator and response a revised `ValidateError` in mosec when validating failed? 
It is optional by server developer.

**Comment by kemingy** [comment]
> Maybe we could insert an msgspec-based validator and response a revised `ValidateError` in mosec when validating failed? It is optional by server developer.

Yes, we can do that. There is a `ValidationError` for this purpose because mosec used to have a pydantic validator (not in this repo history). I think it can be one of the mixin. You can try it. Feel free to ask questions.

**Comment by kemingy** [comment]
The mixin might be a little complex due to the multiprocessing spawn context. Let me create a draft for you. But feel free to review and leave some comments.

**Comment by kemingy** [comment]
Closing this one since it's done by #352. Will track the OpenAPI doc in #359.
