### ISSUE TITLE
unload model automatic

### ISSUE THREAD

**Issue by lfxx** [mosecorg/mosec#393]
### Describe the feature

can we add a function which can unload model if there is no request received within one day.And model will be loaded again if new request be receive.

### Why do you need this feature?

This is very useful on GPU memory urgent server.

**Comment by lfxx** [comment]
I have implented this on my own server framework.But i still hope mosec can have this funcion.

**Comment by gaocegege** [comment]
Thanks for the issue.

By the way, could you tell me in what scenarios Mosec is being used in your case?

**Comment by lfxx** [comment]
> Thanks for the issue.
> 
> By the way, could you tell me in what scenarios Mosec is being used in your case, and how do you know mosec?

I learned about mosec from a blogger named oldpan, and I will use mosec to build an AI service for frontend to use.
i hope mosec can add this funtion soon since it is a bit of complex for me to implement this on mosec cause i am not a rust expert.
