### ISSUE TITLE
bug: 'site-packages/mosec/bin/mosec' not found on macOS M1

### ISSUE THREAD

**Issue by oliverhu** [mosecorg/mosec#507]
### Describe the bug

Tried the `Echo Example` in the [mosec documentation](https://mosec.readthedocs.io/en/latest/examples/echo.html) and failed to launch.

### To Reproduce
Install mosec via `pip install -U mosec`

Then run the exact same code in echo.py
```
import time
from typing import List

from mosec import Server, ValidationError, Worker, get_logger

logger = get_logger()


class Preprocess(Worker):
    """Sample Class."""

    example = {"time": 0}

    def forward(self, data: dict) -> float:
        logger.debug("pre received %s", data)
        # Customized, simple input validation
        try:
            count_time = float(data["time"])
        except KeyError as err:
            raise ValidationError(f"cannot find key {err}") from err
        return count_time


class Inference(Worker):
    """Sample Class."""

    example = [0, 1e-5, 2e-4]

    def forward(self, data: List[float]) -> List[float]:
        logger.info("sleeping for %s seconds", max(data))
        time.sleep(max(data))
        return data


class Postprocess(Worker):
    """Sample Class."""

    def forward(self, data: float) -> dict:
        logger.debug("post received %f", data)
        return {"msg": f"sleep {data} seconds"}


if __name__ == "__main__":
    server = Server()
    server.append_worker(Preprocess)
    server.append_worker(Inference, max_batch_size=32)
    server.append_worker(Postprocess)
    server.run()

```
and run with:
`python echo.py`

### The mosec version

mosec-0.8.3
Python 3.10.0
macOS Sonoma, M1 Macbook Pro

### Additional context

Only fails in macOS, **it works on my Linux box.**

**Comment by kemingy** [comment]
There is no ARM release now. I think we can add it since GitHub has ARM runners.

Related to the upstream issues:
- https://github.com/pypa/cibuildwheel/pull/1700

**Comment by kemingy** [comment]
Hi @oliverhu, 0.8.4 is released with macOS ARM64 support. You can try it with `pip install mosec==0.8.4` on macOS M1.

**Comment by oliverhu** [comment]
@kemingy thanks for the prompt response & fix!

**Comment by heibaidaolx123** [comment]
Hi @kemingy 
I got this similar error when `server.run()` on arm64 linux with mosec 0.8.4 and 0.9.0:
```
FileNotFoundError: [Errno 2] No such file or directory: PosixPath('/usr/local/python3.11.10/lib/python3.11/site-packages/mosec/bin/mosec')
```
and there's no bin folder under  ./site-packages/mosec


Any idea?

**Comment by kemingy** [comment]
@heibaidaolx123 mosec doesn't have a Linux ARM pre-built wheel. You will need to package by running `make package`.

- related to https://github.com/mosecorg/mosec/issues/604 switch to maturin will make this easy

What's your use case?

**Comment by heibaidaolx123** [comment]
@kemingy I just want to serve a small model on an arm64 linux server.
Will try building from the source.
Thanks.

**Comment by kemingy** [comment]
> [@kemingy](https://github.com/kemingy) As no `rust-toolchain.toml` in the repo, which version of rust do you use to build the package?

I think rust>=1.80 will work.

**Comment by heibaidaolx123** [comment]
@kemingy 
I tried 1.83.0 and 1.80.0, both failed due to the errer when compiling time-0.3.34, as reported [here](https://github.com/time-rs/time/issues/693).
Rust 1.79.0 works.

**Comment by kemingy** [comment]
> [@kemingy](https://github.com/kemingy) I tried 1.83.0 and 1.80.0, both failed due to the errer when compiling time-0.3.34, as reported [here](https://github.com/time-rs/time/issues/693). Rust 1.79.0 works.

Hi @heibaidaolx123, from 0.9.1, we support most of the platforms. You can try to install with `pip install mosec` directly on ARM Linux.
