### ISSUE TITLE
feat: Add "Go to Top" Button for Improved Navigation

### ISSUE THREAD

**Issue by Mefisto04** [mosecorg/mosec#577]
### Describe the feature

A "Go to Top" button that appears when the user scrolls down the page. When clicked, it should smoothly scroll the user back to the top of the page. This feature enhances navigation, making it more user-friendly, especially for lengthy documentation pages.

### Why do you need this feature?

Navigating long documentation can be cumbersome, requiring multiple scrolls to get back to the top. A "Go to Top" button would provide a convenient way for users to return to the top of the page with a single click, improving the overall user experience and accessibility of the documentation site.

### Additional context

This button could be styled to appear discretely at the bottom right corner of the screen when the user scrolls down. It should also smoothly transition the user back to the top to maintain a polished feel. An optional configuration to enable/disable this feature could be considered for user preference.

**Comment by kemingy** [comment]
Press the "Home" button.
