### ISSUE TITLE
What does parallel mean in the Qualitative Comparison

### ISSUE THREAD

**Issue by ziadmoubayed** [mosecorg/mosec#84]
Thanks for this interesting comparison. I am wondering what the `parallel` column is trying to compare exactly? Does it mean the ability to serve different artifacts/models in one service?

**Comment by lkevinzc** [comment]
Hi @ziadmoubayed, thanks for your question!

Basically the `parallel` means `parallel computing`. So after we define the `Worker` class, which can represent either the pre/post-processing or model forward, we can also specify how many processes we want to run to execute tasks in parallel. 

It is different from multiple artifacts/models in one service.

Hope this clarifies, thanks!
